# MkDocs configuration for Netlify builds

site_name: pg_stat_monitor Documentation
site_description: Documentation
site_author: Percona LLC
copyright: Percona LLC, &#169; 2022
  
repo_name: percona/pgsm-docs
repo_url: https://github.com/percona/pgsm-docs
edit_uri: edit/main/docs/

use_directory_urls: false

# Theme settings
theme:
  name: material
  logo: _images/percona-logo.svg
  favicon: _images/percona-favicon.ico
  custom_dir: _resource/overrides
  font:
    text: Poppins

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: percona-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Theme features

  features:
    - search.share
    - search.highlight
    - content.action.copy
    - content.action.view
    - content.action.edit
    - content.tabs.link
    - navigation.top
    - navigation.tracking


extra_css:
  - https://unicons.iconscout.com/release/v3.0.3/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css
  - css/version-select.css
  - css/toctree.css
  - css/percona.css

extra_javascript:
  - js/version-select.js

markdown_extensions:
  - attr_list
  - toc:
      permalink: True
  - admonition
  - footnotes
  - def_list   # https://michelf.ca/projects/php-markdown/extra/#def-list
  - meta
  - smarty:
        smart_angled_quotes: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
        linenums: false
  - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg
  #- plantuml_markdown

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
  - section-index # Adds links to nodes - comment out when creating PDF
#  - htmlproofer # Uncomment to check links - but extends build time significantly
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null   


extra:
  version:
    provider: mike
  homepage: https://docs.percona.com
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - index.md
  - Installation and setup:
    - "Install": "install.md"
    - "Set up": "setup.md"
  - User guide:
    - "User guide": "user_guide.md"
    - views.md
    - functions.md
    - pmm.md
  - Reference:
    - pg_stat_monitor view reference:
      - reference.md
    - comparison.md
    - configuration.md
  - Release notes:
    - release_notes.md
  - contributing.md
# - Version Selector: "../"